### ISSUE TITLE
Cannot load metadata fields

### ISSUE THREAD

**Issue by kcopsguru** [awslabs/visual-asset-management-system#114]
Hi, I am running the commit d0736e50b8d6a31e9df189d74cc3ecb1c55a9cff. The app was not able to load the metadata when creating a new asset. To re-produce the error:

1. Create a metadata field in metadata schema.
2. Create a new asset, enter the basic info and client next.

On the Asset Metadata screen, it couldn't load the metadata field.

![image](https://github.com/awslabs/visual-asset-management-system/assets/88400295/9b59ea0d-ad69-47fc-8b4d-d67e8f096ef2)

**Comment by ravij3** [comment]
@kcopsguru : Thank you for bringing this to our attention. We will get back to you on this.

**Comment by archieco** [comment]
Hi @kcopsguru, this is a problem for projects that use metadata schemas without uploading a controlled list csv file on the metadata schema screen. So, a workaround in the immediate term is to upload an empty file. We expect to improve this over time. If you're interested in contributing a fix, potentially a solution is to provide a fallback mechanism to loading the `controlledlist.csv` from S3 in `ControlledMetadata.tsx`. Hope this helps.

**Comment by kcopsguru** [comment]
@archieco thanks for the info. I only created a metadata field with string type. In this case, do I still need to upload a controlled list csv file?

**Comment by archieco** [comment]
This is addressed by #120
