### ISSUE TITLE
Asset Upload button not working in Firefox

### ISSUE THREAD

**Issue by rogerkenny** [awslabs/visual-asset-management-system#121]
Repro:
Try to upload an asset through the web interface on Firefox.
Clicking the Upload button has no effect.

Firefox console error: Uncaught (in promise) TypeError: window.showOpenFilePicker is not a function

Mac OS 12.6.6 (21G646)
Firefox 102.13.0esr (64-bit)

**Comment by ravij3** [comment]
Hi @rogerkenny: To support resumable uploads for large objects we made a decision to use the FileSystemAccess API. The support for this API is currently only available in Chrome and Edge browser.

https://caniuse.com/native-filesystem-api
