### ISSUE TITLE
Creating a comments page

### ISSUE THREAD

**Issue by ashkevin22** [awslabs/visual-asset-management-system#126]
I'm interning at Amazon this Summer and my internship project was to create a comment system to review assets which I implemented into VAMS. Is this a feature that you would like to possibly add? I am working on creating a PR now.

PR #127

**Comment by ashkevin22** [comment]
After doing some more testing, I found out that there is some weird behavior with the comments because of the disabled versions ([line 152 in backend/backend/handlers/assets/uploadAsset.py](https://github.com/awslabs/visual-asset-management-system/blob/d988ab37594a9b2154d7606f256b5476e3d4ee6d/backend/backend/handlers/assets/uploadAsset.py#L152C4-L155C64)). Basically because there is no S3 version information about the assets, the comments will attach to every version of an asset. I don't think that there is really any way for me to fix this, but it is something to be aware of.
<img width="588" alt="Screenshot 2023-08-16 at 1 03 14 PM" src="https://github.com/awslabs/visual-asset-management-system/assets/65938312/305b4a00-5c87-43cd-b383-0eea536c5f14">

**Comment by archieco** [comment]
Thanks again for the feature @ashkevin22
