### ISSUE TITLE
Creating workflows with the same name in different VAMS stacks

### ISSUE THREAD

**Issue by SnitavetsIV** [awslabs/visual-asset-management-system#134]
Steps to re-produce:

1. Deploy two VAMS instances (A and B) in the same account and region.
2. Create a new workflow named test in instance A.
3. Create a new workflow also named test in instance B.
4. The workflow UI showed that both workflows are created successfully. However, behind the scene, the second workflow failed to be created. When users execute the test workflow in instance B, the test workflow in instance A is executed.
5. When the test workflow is deleted in instance B, the workflow in instance A is also deleted

**Comment by archieco** [comment]
Resolved by #138
