### ISSUE TITLE
Does not build on windows due to incorrect argument in ./web/package.json

### ISSUE THREAD

**Issue by copystart** [awslabs/visual-asset-management-system#63]
Current main branch does not build on Windows due incorrect argument in ./web/package.json with the "postinstall" scripts. Error can be seen when issuing "yarn install" command. 

"Del" command must be replace with "del-cli"

Previous:
"postinstall": "patch-package && del ./node_modules/online-3d-viewer/libs/loaders/occt-import-js-worker.js && del ./node_modules/online-3d-viewer/libs/loaders/occt-import-js.js && del ./node_modules/online-3d-viewer/libs/loaders/occt-import-js.license.md && del ./node_modules/online-3d-viewer/libs/loaders/occt-import-js.wasm"

New:
"postinstall": "patch-package && del-cli ./node_modules/online-3d-viewer/libs/loaders/occt-import-js-worker.js && del-cli ./node_modules/online-3d-viewer/libs/loaders/occt-import-js.js && del-cli ./node_modules/online-3d-viewer/libs/loaders/occt-import-js.license.md && del-cli ./node_modules/online-3d-viewer/libs/loaders/occt-import-js.wasm"

**Comment by archieco** [comment]
Resolved by #64
