### ISSUE TITLE
Hitting "Execute Workflow" button from the assets page doesn't work

### ISSUE THREAD

**Issue by lmarbleAWS** [awslabs/visual-asset-management-system#69]
When you click the "Execute Workflow" button on an assets page, you are able to select the appropriate workflow but nothing actual happens. In order to run a workflow on an asset, you must access the workflow from the workflow page and then select the asset to execute the workflow on.

**Comment by ravij3** [comment]
Thanks @lmarbleAWS!

I was able to replicate this and I have a fix for this in another branch. Will check it in soon.
