### ISSUE TITLE
Deleting assets that have no preview file errors and corrupts the asset state

### ISSUE THREAD

**Issue by scheurik** [awslabs/visual-asset-management-system#97]
Deleting an existing asset that was uploaded with no preview file errors to the user. It does a partial delete behind the scenes which corrupts the asset (can be viewed on the errors when you try to edit the asset).

It seems on upload of an asset without a preview file it still puts a preview entry in with a .undefined extension. Below is a cloudwatch screenshot of the lambda function erroring on delete.

This is on the latest VAMS main branch code. 

![image](https://github.com/awslabs/visual-asset-management-system/assets/276052/eae8c504-31a0-4c5b-90d6-6118cb98f35e)

**Comment by ravij3** [comment]
Fixed with #108
